import * as mongoose from 'mongoose';

export const InstructorSchema = new mongoose.Schema({
  register_type: String,
  school_inep_id_fk: String,
  inep_id: String,
  name: String,
  email: String,
  nis: String,
  birthday_date: String,
  sex: Number,
  color_race: Number,
  filiation: Boolean,
  filiation_1: String,
  filiation_2: String,
  nationality: Number,
  edcenso_nation_fk: Number,
  edcenso_uf_fk: Number,
  edcenso_city_fk: Number,
  deficiency: Boolean,
  deficiency_type_blindness: Boolean,
  deficiency_type_low_vision: Boolean,
  deficiency_type_deafness: Boolean,
  deficiency_type_disability_hearing: Boolean,
  deficiency_type_deafblindness: Boolean,
  deficiency_type_phisical_disability: Boolean,
  deficiency_type_intelectual_disability: Boolean,
  deficiency_type_multiple_disabilities: Boolean,
  deficiency_type_autism: Boolean,
  deficiency_type_gifted: Boolean,
  hash: Number,
});
